version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - CORS_ORIGINS=http://localhost:3000
    volumes:
      - ./backend/data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3      
    networks:
      - meal-network

  frontend:
    build: 
      context: ./frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - meal-network
    volumes:
      - ./frontend/runtime-config:/runtime-config
      - ./ssl-certs:/etc/nginx/ssl
    environment:
      - HTTPS_ENABLED=true
    depends_on:
      - backend

networks:
  meal-network:
    driver: bridge