---
services:
  backend:
    build:
      context: ./backend
    image: abuhamsa/meal-planner-backend:latest    
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env-prod
    volumes:
      - ./backend/data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3      
    networks:
      - meal-network

  frontend:
    build: 
      context: ./frontend
    image: abuhamsa/meal-planner-frontend:latest  
    ports:
      - "80:80"
      - "5173:443"
    networks:
      - meal-network
    volumes:
      - ./frontend/runtime-config:/runtime-config
      - ./frontend/ssl-certs:/etc/nginx/ssl
    environment:
      - HTTPS_ENABLED=true
    depends_on:
      - backend

networks:
  meal-network:
    driver: bridge