version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./meals.db:/app/meals.db
      - ./migrations:/app/migrations
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production